import js from '@eslint/js';
import tseslint from 'typescript-eslint';
import reactHooks from 'eslint-plugin-react-hooks';

/**
 * Deliberately lean. eslint-config-next 15 still assumes ESLint 8's rc
 * format, and the rules that actually catch bugs in this codebase are the
 * hooks ones (a stale dependency array is exactly what made the grid show
 * an empty column after copy-forward) plus unused-symbol detection.
 */
export default tseslint.config(
  {
    // next-env.d.ts is generated by Next on every build.
    ignores: [
      '.next/**',
      'node_modules/**',
      'next-env.d.ts',
      'src/db/migrations/**',
      'openapi/**',
      'test-results/**',
    ],
  },
  js.configs.recommended,
  ...tseslint.configs.recommended,
  {
    plugins: { 'react-hooks': reactHooks },
    rules: {
      ...reactHooks.configs.recommended.rules,
      '@typescript-eslint/no-unused-vars': [
        'error',
        { argsIgnorePattern: '^_', varsIgnorePattern: '^_' },
      ],
      // Domain code intentionally takes `unknown` at the wire boundary and
      // narrows with Zod; a blanket ban here would fight that.
      '@typescript-eslint/no-explicit-any': 'warn',
    },
  },
);
